### PR TITLE
Fix rusti for latest nightly

### PR DESCRIPTION
**Pull request by bjorn3**
Instead of using LLVM JIT, this just builds a binary and executes it.

# TODO
* [X] Fix .type
* [x] Use items from previously compiled dylib

### CODE REVIEW

**Comment by murarth** [comment]
I understand the frustration that rusti is tied to a very old nightly build (now over a year and a half old), but I don't think I can get behind this kind of change.

This method of input compilation is inherently limited. As you acknolwedge, it breaks the `.type` command. It's a clear step backward in terms of trying to achieve the goal of a true Rust REPL.

**Comment by dwijnand** [comment]
For `.type` is it not possible to synthesis a source file around a Rust expression such that the type of the expression can be extracted?

**Comment by bjorn3** [comment]
> For .type is it not possible to synthesis a source file around a Rust expression such that the type of the expression can be extracted?

Yes, I just haven't implemented it jet.

**Comment by bjorn3** [comment]
I am working on using dylibs instead of executables, so that that for example statics can be shared and don't get reset after every command (new) and functions don't get compiled more than once (like before this PR).

**Comment by bjorn3** [comment]
> it'll be nice to have a full-fledged rust repl for stable.

At least .type won't work on stable

**Pull request closed without merging**
